version: '3.8'
services:
  internetbanking:
    image: vickydockek11/ib-image:latest
    ports:
      - "81:80"
    deploy:
      replicas: 10
    volumes:
      - /var/lib/internetbanking
  mobilebanking:
    image: vickydockek11/mb-image:latest
    ports:
      - "82:80"
    deploy:
      replicas: 10
    volumes:
      - /var/lib/mobilebanking
  insurance:
    image: vickydockek11/i1-image:latest
    ports:
      - "83:80"
    deploy:
      replicas: 10
    volumes:
      - /var/lib/insurance
  loan:
    image: vickydockek11/loans-image:latest
    ports:
      - "84:80"
    deploy:
      replicas: 10
    volumes:
      - /var/lib/loan
